[connectsetting]
  authpassword = "passwd"
  authusername = "ANT"
  ip = "127.0.0.1"
  port = "8482"
  supportremote = false

[LoggerSetting]
  LoggingLevel = 5
  LoggingOutput = "file"

[Enginesetting]
  MaxActiveTorrents     = 5
  SocksProxyURL         = ""
  UseSocksproxy         = false
  TorrentDBPath         = "storm.db"
  Tmpdir                = "tmp"
  MaxEstablishedConns   = 100
  DataDir = "download"
  EnableDefaultTrackers = true
  DefaultTrackerList = "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ip.txt"
  DefaultIPBlockList = "http://john.bitsurge.net/public/biglist.p2p.gz"
  disableipv6 = false
  disableipv4 = false

[Torrentconfig]
  bep20 = ""
  debug = false
  defaultstorage = ""
  dhtconfig = ""
  disablepex = false
  disabletcp = false
  disabletrackers = false
  disableutp = false
  downloadratelimit = ""
  extendedhandshakeclientversion = ""
  httpuseragent = ""
  ipblocklist = ""
  listenaddr = ""
  ListenPort = 0
  nodht = false
  noupload = false
  peerid = ""
  seed = false
  uploadratelimit = ""

[Encryptionpolicy]
  disableencryption = false
  forceencryption = false
  prefernoencryption = true