
[connectsetting]
  authpassword = "passwd"
  authusername = "ANT"
  ip = "127.0.0.1"
  port = "8482"
  supportremote = false

[LoggerSetting]
  logginglevel = 5
  loggingoutput = "file"

[enginesetting]
  maxactivetorrents     = 5
  socksproxyurl         = ""
  usesocksproxy         = false
  TorrentDBPath         = "storm.db"
  Tmpdir                = "tmp"
  MaxEstablishedConns   = 80

  [enginesetting.torrentconfig]
    bep20 = ""
    datadir = "download"
    debug = false
    defaultstorage = ""
    dhtconfig = ""
    disableipv6 = false
    disablepex = false
    disabletcp = false
    disabletrackers = false
    disableutp = false
    downloadratelimit = "Unlimited"
    extendedhandshakeclientversion = ""
    httpuseragent = ""
    ipblocklist = ""
    listenaddr = ""
    ListenPort = 0
    nodht = false
    noupload = false
    peerid = ""
    seed = false
    uploadratelimit = "Unlimited"
    defaultTrackerList = "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ip.txt"
    defaultIPBlockList = "http://john.bitsurge.net/public/biglist.p2p.gz"

    [enginesetting.torrentconfig.encryptionpolicy]
      disableencryption = false
      forceencryption = false
      prefernoencryption = true
